GET http://localhost:5000/hak_akses

###
POST http://localhost:5000/hak_akses
Content-Type: application/json

{
    "nama_akses": "admin"
}

###
GET http://localhost:5000/pengguna

###
POST http://localhost:5000/pengguna
Content-Type: application/json

{
    "username": "admin",
    "password": "admin",
    "email": "admin@gmail.com",
    "id_akses" : "1"
}